export const PAGE_NAME = {
    'HOME': 'Home',
    'VIEW_PARTICIPANT': 'View Participant Component',
    'HEALTH_STATUS': 'Participant Health Status',
    'PATIENT_CARE_PLAN': 'Patient Care Plan',
    'PATIENT_CARE_TEAMS': 'Patient Care Team',
    'VIEW_CARE_PLAN': 'View Care Plan',
    'VIEW_CARE_PLAN_DETAILS': 'View CarePlan Details',
    'PATIENT_LIST_FROM_CAREPLAN': 'Patient List From CarePlan',
    'CARE_TEAM_FROM_CARE_PLAN': 'Care Team From Care Plan',
    'EVENT_LOG': 'Event Log',
    'ASSESSMENT_ANSWER': 'Assessment Answer',
    'SEIZURE_QUESTIONNAIRE':'Seizure Questionnaire',
    'PARTICIPANT_PROFILE_FROM_CAREPLAN':'View Participant Component from Careplan',
    'PATIENT_LIST_FROM_PATIENT_PROFILE': 'Patient List From Patient Profile',
    'CHAT': 'Chat',
    'VIEW_CARE_PLAN_DETAILS_FROM_PATIENTPROFILE': 'View CarePlan Details from Patient Profile',
    'MEDICAL_RECORD': 'Medical Record',
    'CARETEAM_FROM_CAREPLAN_OF_PATIENPROFILE': 'Care Team From Care Plan of Patient Profile',
    'PATIENT_LIST_FROM_CAREPLAN_OF_PATIENTPROFILE': 'Patient List From CarePlan of Patient Profile',
    'ASSESSMENT':'Assessment',
    'ACCESS_MANAGEMENT':'Access Management'
};
export const LABEL_NAME = {
    'HOME': 'Home',
    'PARTICIPANT_LIST': 'Patient List',
    'HEALTH_STATUS': 'Health Status',
    'VITAL_DETAILS': 'Vital Details',
    'CARE_PLANS': 'Care Plans',
    'CARE_TEAM': 'Care Team',
    'EVENT_LOG': 'Event Log',
    'ASSESSMENT_ANSWER': 'Assessment',
    'SEIZURE_QUESTIONNAIRE':'Seizure Questionnaire',
    'CHAT': 'Chat',
    'MEDICAL_RECORD': 'Medical Record',
    'ASSESSMENT':'Questionnaires',
    'ACCESS_MANAGEMENT':'Access Management',
    'USER_MANAGEMENT':'User Management',
    'USERS':'Users'
};