export const ERROR_MESSAGES = {
    'required': 'Required',
    'client_name': 'Please enter a client name.',
    'client_name_onlyChar': 'Invalid Client Name entry- This entry can only contain letters.',
    'hospital_group': 'Please enter the name of the hospital group.',
    'hospital_group_onlyChar': 'Invalid Hospital Group entry- This entry can only contain letters.',
    'deployment_type': 'Please select deployment type.',
    'postal_code': 'Invalid Postal Code entry - This entry can only contain numbers.',
    'contract_start_date': 'Please enter a start date.',
    'date_of_birth':'Please enter date of birth',
    'gender':'Please seelct a gender',
    'contract_time': 'Please enter the contract term.',
    'first_name': 'Please enter a first name',
    'last_name': 'Please enter a last name',
    'alphanumeric': 'Please enter data in Alphanumeric',
    'first_name_onlyChar': 'Invalid First Name entry - This entry can only contain letters.',
    'job_title': 'Please enter a job title',
    'job_title_onlyChar': 'Invalid Job Title entry - This entry can only contain letters.',
    'email_id': 'Please enter an email address.',
    'phone_number': 'Please enter a 10-digit phone number.',
    'phone_number_invalid': 'Invalid Phone Number entry - This entry can only contain numbers.',
    'invalidEmailAddress': 'Please enter a valid email address',
    'invalidPassword': 'Invalid password. Password must be at least 6 characters long, and contain a number.',
    'minlength': `Minimum length`,
    'onlyNumbers': 'Enter only numbers',
    'role_name': 'Please enter a role name',
    'role_type': 'Please select a role type',
    'user_name': 'Please enter user name',
    'password': 'Please enter password',
    'invalidName': 'Please enter a valid name',
    'maxCharAllowed' : 'Exceeds max character',
    'confirmPassword' : 'Incorrect password.',
    'addressValidate': 'Please enter a valid address',
    'cityValidate': 'Please enter a valid city',
    'stateValidate': 'Please enter a valid state',
    'decimalValue': 'Enter valid values',
};

