export const FEATURE_CONSTANT = {
    'GET_APPLICATION': '/GetApplications',
    'GET_LIGAL_INTITY': '/usage/legalEntitys',
    'GET_LEGAL_ENTITY_NEW': '/GetLegalEntities/',
    'GET_APPLICATION_USAGE_DETAILS': '/GetApplicationDetails',
    'GET_APPLICATION_SERVICES_DETAILS': '/getApplicationServicesDetails',
    'GET_APPLICATION_TOTAL': '/getApplicationTotals',
    'ADD_NEW_APPLICATION': '/addApplication',
    'ALL_LUMPSUMS': '/lumpsums',
    'ADD_LUMPSUMS': '/lumpsums/add',
    'UPDATE_LUMPSUMS': '/lumpsums/update',
    'GET_DASHBOARD_DETAILS': '/dashboard',
    'GET_RIGIONS': '/GetRegions',
    'GET_LEGAL_ENTITYTIES': '/common/getLegalEntitys/',
    'GET_SKILL_TEAMS': '/common/getSkillteams',
    'GET_ALL_SERVICES': '/common/getServices',
    'GET_ALL_STATUS': '/common/getStatus',
    'ADD_SERVICE': '/Volume/addUser',
    'ADD_VOLUME_OPCOST': '/Volume/add',
    'ADD_USAGE': '/usage/add',
    'ADD_LEGALENTITY':  '/volume/physical/addlegalEntity',
    // 'ADD_VOLUME': '/Volume/AddVolumeForOpcost',
    // 'GET_VOLUME_DETAILS': '/Volume/getVolumeOpcostDetails'
    'DELETE_USER': '/usage/delete',
    'UPDATE_USER': '/usage/update',
    'UPDATE_VOLUME_OPCOST': '/Volume/update',
    'CHANGE_REGIONS': '/common/getChangeReason',
    'GET_PURCHASE_ORDERS': '/common/getPurchaseOrders',
    'GET_OP_COST_VOLUME_DETAILS': '/getVolumeDetails/',
    'GET_APPROVAL_DETAILS': '/approval/getAllRecords',
    'GET_FILTER_USAGE_DETAILS': '/filterApps/',
    'GET_ITMMS_APPLICATION_DETAILS': '/getITMSApplications/',
    'CREATE_GROUP': '/Volume/createBundle',
    'SPREAD_VOLUME': '/Volume/spreadVolume',
    'UPDATE_GROUP': '/Volume/updateBundle',
    'UPDATE_PHYSICAL_TABLE': '/Volume/updatePhysicalVolume',
    'GETVOLUME_PHYSICAL_SKILLTEAM': '/volume/physical/getSkillTeam',
    'GETVOLUME_PHYSICAL_LEGALENTITY': '/Volume/getLegalEntities',
    'GETVOLUME_PHYSICAL_SERVICECATALOG': '/volume/physical/getServiceCatalog',
    'GETVOLUME_PHYSICAL_ADDSERVICE': '/volume/physical/addservice',
    'DELETE_GROUP': '/Volume/deleteBundle',
    'APPROVAL_SAVE': '/approval/saveApprovals',
    'APPROVAL_DOWNLOAD': '/approval/download'
}
